### ISSUE TITLE
Error with CanCan when entering solidus backend

### ISSUE THREAD

**Issue by harinsa** [AlchemyCMS/alchemy-solidus#4] opened 2015-12-20 13:15 UTC
I get the following error when trying to visit the admin section of solidus.

The accessible_by call cannot be used with a block 'can' definition. The SQL cannot be determined for :index Spree::Order(id: integer, number: string, item_total: decimal, total: decimal, state: string, adjustment_total: decimal, user_id: integer, completed_at: datetime, bill_address_id: integer, ship_address_id: integer, payment_total: decimal, shipment_state: string, payment_state: string, email: string, special_instructions: text, created_at: datetime, updated_at: datetime, currency: string, last_ip_address: string, created_by_id: integer, shipment_total: decimal, additional_tax_total: decimal, promo_total: decimal, channel: string, included_tax_total: decimal, item_count: integer, approver_id: integer, approved_at: datetime, confirmation_delivered: boolean, guest_token: string, canceled_at: datetime, canceler_id: integer, store_id: integer, approver_name: string, frontend_viewable: boolean)

Here is the stack trace: 
https://gist.github.com/harinsa/7e5226cb552b0e17ef13

**Comment by eric1234** [comment] 2016-02-15 21:01
I get this also. I tracked it down a bit although I haven't yet come up with a great solution.

The problem is that really there is only one `Ability` class and all other registered abilities have their rules "merged" into the final ability. In our case the final ability is [`Alchemy::Permissions`](https://github.com/AlchemyCMS/alchemy_cms/blob/master/lib/alchemy/permissions.rb). While we can merge rules from different abilities we only have one set of aliases which are defined by that final ability.

In Alchemy the aliases are the [cancan defaults](https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/ability.rb#L401) + [a few alchemy special ones](https://github.com/AlchemyCMS/alchemy_cms/blob/master/lib/alchemy/permissions.rb#L196).

Solidus on the other hand [clears the cancan defaults and just adds it's own](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/ability.rb#L37).

Since Solidus is merged into Alchemy we use Alchemy's aliases. Since Alchemy builds on cancan's defaults `:index` is aliased to `:read`. This means when we check the ability to `:index` a `Spree::Order` we also end up checking the ability to `:read` a `Spree::Order`. This ends up selecting [this rule](https://github.com/solidusio/solidus/blob/master/core/lib/spree/permission_sets/default_customer.rb#L9-L11). This rule is not compatible with `:index` since it is a block-style check and `:index` needs only query checks.

Took me a while to track down why this was happening in Solidus but not Spree. Turns out it does happen in Spree if you are a non-admin user who can manage orders. But 99% of spree stories just have "admin" users which has [a special shortcut in Spree that avoids creating all the rules and just has one rule that allows all permissions](https://github.com/spree/spree/blob/master/core/app/models/spree/ability.rb#L39-L40). This means the problematic rule doesn't end up conflicting with the incompatible aliases of Alchemy. This shortcut has been removed in Solidus due to  the new permission sets feature.

I'm not sure the exact solution as we don't want to just switch things around have have Alchemy use Spree's aliases.

I'm thinking the best solution would be to keep both abilities separate so they can maintain their own rules and aliases. Then have a ability in this add-on that proxies to the right alias depending on if the object for which we are checking permission is a `Spree::` object or an `Alchemy::` object. We also need to cover the case where the app needs to still register it's own rules for it's own objects so perhaps monkey-patch both `register_ability` on both systems to actually register the ability on our custom proxies ability? But that all sounds fairly complicated so I am wondering if there is a better solution. Right now I am testing the below hack which emulated Spree's behavior as a stop-gap:

```
Spree::Ability.class_eval do
  module Hack
    def initialize user
      if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
        can :manage, :all
      else
        super
      end
    end
  end
  prepend Hack
end
```

**Comment by tvdeyen** [comment] 2016-09-07 06:44
Can this be closed now?

**Closed** 2016-09-07 06:44 UTC
